// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [{type: 'autogenerated', dirName: '001-ros2-module-spec'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [{type: 'autogenerated', dirName: '004-vla-module'}],
    },
    {
      type: 'category',
      label: 'Module 5: Digital Twin',
      items: [{type: 'autogenerated', dirName: '005-digital-twin-module'}],
    },
    {
      type: 'category',
      label: 'Module 6: NVIDIA Isaac',
      items: [{type: 'autogenerated', dirName: '006-nvidia-isaac-module'}],
    },
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],
};

export default sidebars;